import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/navigation";
import { ThemeProvider, createTheme, makeStyles } from "@mui/material/styles";
import { theme } from "@/components/theme";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ThemeProvider theme={theme}>
				<body>
					<NavigationBar>{children}</NavigationBar>
				</body>
			</ThemeProvider>
		</html>
	);
}
